services:
  simulator-user:
    build:
      context: ./services/simulator
    environment:
      SERVICE_NAME: user
    ports:
      - "8101:8000"
    labels:
      - "aiops_service=user"
    networks:
      - aiops-net

  simulator-auth:
    build:
      context: ./services/simulator
    environment:
      SERVICE_NAME: auth
    labels:
      - "aiops_service=auth"
    ports:
      - "8102:8000"
    networks:
      - aiops-net

  simulator-orders:
    build:
      context: ./services/simulator
    environment:
      SERVICE_NAME: orders
    labels:
      - "aiops_service=orders"
    ports:
      - "8103:8000"
    networks:
      - aiops-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - aiops-net

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4318:4318" # OTLP HTTP
    networks:
      - aiops-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - aiops-net

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/config.yml:ro
    networks:
      - aiops-net

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./observability/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aiops-net
    depends_on:
      - loki

  detector:
    build:
      context: ./services/detector
    ports:
      - "8000:8000"
    volumes:
      - ./models/artifacts:/app/models/artifacts:ro
    environment:
      - DETECTOR_MODEL_PATH=/app/models/artifacts/detector.joblib
    networks:
      - aiops-net

  predictor:
    build:
      context: ./services/predictor
    ports:
      - "8001:8001"
    volumes:
      - ./models/artifacts:/app/models/artifacts:ro
    environment:
      - PREDICTOR_MODEL_PATH=/app/models/artifacts/predictor.joblib
      - PREDICTOR_THRESHOLD=0.45
    networks:
      - aiops-net

  rca:
    build:
      context: ./services/rca
    ports:
      - "8002:8002"
    volumes:
      - ./models/rca:/app/models/rca:ro
      - ./data/processed:/app/data/processed:ro
      - ./models/rca/out:/app/models/rca/out
    networks:
      - aiops-net

networks:
  aiops-net:
    driver: bridge
