global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # -------------------------
  # Simuladores (microservicios l√≥gicos)
  # -------------------------
  - job_name: "simulators"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - simulator-user:8000
          - simulator-auth:8000
          - simulator-orders:8000

  # -------------------------
  # Prometheus self-scrape
  # -------------------------
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "detector"
    static_configs:
      - targets: ["detector:8000"]

  - job_name: "predictor"
    static_configs:
      - targets: ["predictor:8001"]

  - job_name: "rca"
    static_configs:
    - targets: ["rca:8002"]

